version: '3.8'

services:
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: tao
      MONGO_INITDB_ROOT_PASSWORD: 123456qwe
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ping:1})"]
      interval: 5s
      timeout: 3s
      retries: 5
