name: MainTest
on:
  push:
    branchs:
      - main
    branches-ignore:
      - dev
  pull_request:
    branches:
    branches-ignore:
      - main
      - dev

jobs:
  test:
    name: Lint-UT
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: '6.0'
          mongodb-username: 'tao'
          mongodb-password: '123456qwe'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status $(go list ./... | grep -v vendor)

      - name: Run Unit tests.
        run: |
          chmod +x test.sh
          ./test.sh

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
